Enforce setting password and improve credentials check

diff --git a/charts/postgres/templates/init-scripts-configmap.yaml b/charts/postgres/templates/init-scripts-configmap.yaml
--- a/charts/postgres/templates/init-scripts-configmap.yaml
+++ b/charts/postgres/templates/init-scripts-configmap.yaml
@@ -43,6 +43,11 @@ data:
     #!/bin/sh
     set -e
 
+    if [ -z "${REPLICATION_USER}" ] || [ -z "${REPLICATION_PASSWORD}" ]; then
+      echo "⛔️ No credentials configured. Aborting"
+      exit 1
+    fi
+
     PGUSER="${POSTGRES_USER}" psql -v ON_ERROR_STOP=1 -v REPL_USER="${REPLICATION_USER}" -v REPL_PASS="${REPLICATION_PASSWORD}" <<'EOSQL'
       SELECT quote_ident(:'REPL_USER') AS user \gset
       SELECT quote_literal(:'REPL_PASS') AS pass \gset
diff --git a/charts/postgres/templates/replication-standby-init-configmap.yaml b/charts/postgres/templates/replication-standby-init-configmap.yaml
--- a/charts/postgres/templates/replication-standby-init-configmap.yaml
+++ b/charts/postgres/templates/replication-standby-init-configmap.yaml
@@ -15,17 +15,22 @@ data:
     #!/bin/bash
     set -e
 
+    if [ -z "${REPLICATION_USER}" ] || [ -z "${REPLICATION_PASSWORD}" ]; then
+      echo "⛔️ No credentials configured. Aborting"
+      exit 1
+    fi
+
     primary_host="{{ tpl .Values.replication.primary.host . }}"
     primary_port="{{ .Values.replication.primary.port }}"
     pgpass_file="{{ include "postgres.runDir" . }}/replication.pgpass"
 
-    # We need to mask ':' in this file
+    # We need to mask ':' in this file, interpreter must be bash
     echo "${primary_host}:${primary_port}:replication:${REPLICATION_USER//:/\\:}:${REPLICATION_PASSWORD//:/\\:}" > "${pgpass_file}"
     chmod 600 "${pgpass_file}"
     echo "✅ ${pgpass_file} created"
 
     if [ -d "${PGDATA}" ]; then
-      echo "${PGDATA} already exists, skipping standby initialization..."
+      echo "⚠️ ${PGDATA} already exists. Skipping standby initialization"
       exit 0
     fi
 
